services:
  pzserver:
    container_name: pz-unstable
    build:
      context: .
    restart: unless-stopped

    environment:
      SERVER_NAME: ${SERVER_NAME:-servertest}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-}
      STEAM_BRANCH: ${STEAM_BRANCH:-unstable}
      UPDATE_ON_START: ${UPDATE_ON_START:-true}
      TZ: ${TZ:-America/Sao_Paulo}
      BACKUP_ENABLED: ${BACKUP_ENABLED:-true}
      BACKUP_TIME: ${BACKUP_TIME:-04:30}
      BACKUP_LOCAL_DIR: /backups
      BACKUP_TARGET_DIR: /backup-target
      SHUTDOWN_GRACE_SECONDS: ${SHUTDOWN_GRACE_SECONDS:-180}
      AUTO_DISABLE_UPNP: ${AUTO_DISABLE_UPNP:-true}

    mem_limit: 10g
    memswap_limit: 14g
    shm_size: "1g"

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    volumes:
      - pz_server:/opt/pzserver
      - pz_data:/data
      - ./backups:/backups
      - ${BACKUP_TARGET_PATH:-./backup-target}:/backup-target

    ports:
      - "16261:16261/udp"
      - "16262-16272:16262-16272/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "27015:27015/tcp"

    stdin_open: true
    tty: true

volumes:
  pz_server:
  pz_data:
